### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by Larivact** [ooc-lang/greg#28]
This project seriously lacks documentation. The original peg has a nice and extensive man page – greg has no documentation ... aside from usage examples.

**Comment by fasterthanlime** [comment]
That's very true! It's also unfortunately not maintained. Feel free to go with your own fork :)

**Comment by Larivact** [comment]
Thanks, you might want to [archive](https://help.github.com/articles/archiving-repositories/) the repo to make it clear that it's no longer maintained.
